server:
  port: 9800
  
spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.67.97.224/haha?cloudSqlInstance=deft-landing-244816:us-central1:demo-1&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: hahauser
    password: haha@123