server:
  port: 9800
  
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 

  datasource:
    url: jdbc:mysql://localhost:3306/supriya
    username: sup
    password: Test@123