server:
  port: 9800
  
spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.222.11.208/Employee?cloudSqlInstance=phrasal-catwalk-244908:us-central1:extremedemo&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: gourab
    password: gourab